# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a613937a956362907455bcc607e76de2"
name = "Rewards"
application_url = "https://jm-rewards.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid" ]
  uri = "/webhooks/orders/paid"

  [[webhooks.subscriptions]]
  topics = [ "refunds/create" ]
  uri = "/webhooks/refunds/create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers, write_customers, read_orders, write_app_proxy"

[auth]
redirect_urls = [ "https://jm-rewards.vercel.app/auth/callback" ]

[app_proxy]
prefix = "apps"
subpath = "rewards"
url = "https://jm-rewards.vercel.app/apps/rewards"
