api_version = "2025-10"

[[extensions]]
name = "points-earned-banner"
handle = "points-earned-banner"
type = "ui_extension"
uid = "bd33758e-9baf-bbb4-2918-44cd041660e9f9289860"

[[extensions.targeting]]
module = "./src/PointsEarnedBanner.jsx"
target = "purchase.thank-you.block.render"

[extensions.capabilities]
api_access = true
network_access = true

[extensions.settings]
[[extensions.settings.fields]]
key = "app_url"
type = "single_line_text_field"
name = "App URL"